// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbcTxUkN1k3YPrB9TZeNU3-JETE1XH_A',
    appId: '1:678381542353:android:71290ed879e50ac14bdef0',
    messagingSenderId: '678381542353',
    projectId: 'chat-karo-311c9',
    storageBucket: 'chat-karo-311c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0_Rq-BgOW-TdzGpxmabRUhpaVf0Xcpg',
    appId: '1:678381542353:ios:deccf68c7009855a4bdef0',
    messagingSenderId: '678381542353',
    projectId: 'chat-karo-311c9',
    storageBucket: 'chat-karo-311c9.appspot.com',
    androidClientId: '678381542353-u7umtcl77greqt9sjds5rs9igaf1e6n7.apps.googleusercontent.com',
    iosClientId: '678381542353-hocotle2m2uuopu57l7mql7lmm4c9f9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0_Rq-BgOW-TdzGpxmabRUhpaVf0Xcpg',
    appId: '1:678381542353:ios:7337b2fef7e129a24bdef0',
    messagingSenderId: '678381542353',
    projectId: 'chat-karo-311c9',
    storageBucket: 'chat-karo-311c9.appspot.com',
    androidClientId: '678381542353-u7umtcl77greqt9sjds5rs9igaf1e6n7.apps.googleusercontent.com',
    iosClientId: '678381542353-rulne273nv98pulve1j8f986pkv2to22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
